<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Location_data
{
	public	$ci;
	public 	$provinces = array('Abra','Agusan del Norte','Agusan del Sur','Aklan',					'Albay','Antique','Apayao','Aurora','Basilan','Bataan','Batanes',
					'Batangas','Benguet','Biliran','Bohol','Bukidnon','Bulacan','Cagayan',
		    		'Camarines Norte','Camarines Sur','Camiguin','Capiz','Catanduanes',
		    		'Cavite','Cebu','Compostela Valley','Cotabato','Davao del Norte',
		    		'Davao del Sur','Davao Occidental','Davao Oriental','Dinagat Islands',
		    		'Eastern Samar','Guimaras','Ifugao','Ilocos Norte','Ilocos Sur',
		    		'Iloilo','Isabela','Kalinga','La Union','Laguna','Lanao del Norte',
		    		'Lanao del Sur','Leyte','Maguindanao','Marinduque','Masbate',
		    		'Metro Manila','Misamis Occidental','Misamis Oriental','Mountain Province',
		    		'Negros Occidental','Negros Oriental','Northern Samar','Nueva Ecija',
		    		'Nueva Vizcaya','Occidental Mindoro','Oriental Mindoro','Palawan',
		    		'Pampanga','Pangasinan','Quezon','Quirino','Rizal','Romblon','Samar',
		    		'Sarangani','Siquijor','Sorsogon','South Cotabato','Southern Leyte',
		    		'Sultan Kudarat','Sulu','Surigao del Norte','Surigao del Sur','Tarlac',
		    		'Tawi-Tawi','Zambales','Zamboanga del Norte','Zamboanga del Sur',
		    		'Zamboanga Sibugay');

	public 	$municipalities = array(
			    	'Abra' => array('Bangued','Boliney','Bucay','Bucloc','Daguioman','Danglas',
				    		'Dolores','La Paz','Lacub','Lagangilang','Lagayan','Langiden',
				    		'Licuan-Baay','Luba','Malibcong','Manabo','Peñarrubia','Pidigan',
				    		'Pilar','Sallapadan','San Isidro','San Juan','San Quintin','Tayum',
				    		'Tineg','Tubo','Villaviciosa'),
			    	'Agusan del Norte' => array('Buenavista','Carmen','Jabonga','Kitcharao',
				    		'Las Nieves','Magallanes','Nasipit','Remedios T. Romualdez','Santiago',
				    		'Tubay'),
			    	'Agusan del Sur' => array('Bunawan','Esperanza','La Paz','Loreto',
				    		'Prosperidad','Rosario','San Francisco','San Luis','Santa Josefa',
				    		'Sibagat','Talacogon','Trento', 'Veruela'),
			    	'Aklan' => array('Altavas','Balete','Banga','Batan','Buruanga','Ibajay',
				    		'Kalibo','Lezo','Libacao','Madalag','Makato','Malay','Malinao','Nabas',
				    		'New Washington','Numancia', 'Tangalan'), 
			    	'Albay' => array('Bacacay','Camalig','Daraga','Guinobatan','Jovellar',
				    		'Libon','Malilipot','Malinao','Manito','Oas','Pio Duran','Polangui',
				    		'Rapu-Rapu','Santo Domingo'),
			    	'Antique' => array('Anini-y','Barbaza','Belison','Bugasong','Caluya','Culasi',
			    			'Hamtic','Laua-an','Libertad','Pandan','Patnongon','San Jose',
			    			'San Remigio', 'Sebaste', 'Sibalom','Tibiao','Tobias Fornier',
			    			'Valderrama'),
			    	'Apayao' => array('Calanasan','Conner','Flora','Kabugao','Luna','Pudtol',
			    			'Santa Marcela'),	
			    	'Aurora' => array('Baler','Casiguran','Dilasag','Dinalungan','Dingalan',
			    			'Dipaculao','Maria Aurora','San Luis'),
			    	'Basilan' => array('Akbar','Al-Barka','Hadji Mohammad Ajul','Hadji Muhtamad',
			    			'Lantawan','Maluso','Sumisip','Tabuan-Lasa','Tipo-Tipo','Tuburan',
			    			'Ungkaya Pukan'),
			    	'Bataan' => array('Abucay','Bagac','Dinalupihan','Hermosa','Limay','Mariveles',
			    			'Morong','Orani','Orion','Pilar','Samal'),
			    	'Batanes' => array('Basco','Itbayat','Ivana','Mahatao','Sabtang','Uyugan'),
			    	'Batangas' => array('Agoncillo','Alitagtag','Balayan','Balete','Bauan','Calaca',
			    			'Calatagan','Cuenca','Ibaan','Laurel','Lemery','Lian','Lobo','Mabini',
			    			'Malvar','Mataas na Kahoy','Nasugbu','Padre Garcia','Rosario','San Jose',
			    			'San Juan','San Luis','San Nicolas','San Pascual','Santa Teresita',
			    			'Santo Tomas','Taal','Talisay','Taysan','Tingloy','Tuy'),
			    	'Benguet' => array('Atok','Bakun','Bokod','Buguias','Itogon','Kabayan','Kapangan',
			    			'Kibungan','La Trinidad','Mankayan','Sablan','Tuba','Tublay'),
			    	'Biliran' => array('Almeria','Biliran','Cabucgayan','Caibiran','Culaba','Kawayan',
			    			'Maripipi','Naval'),
			    	'Bohol' => array('Alburquerque','Alicia','Anda','Antequera','Baclayon','Balilihan',
			    			'Batuan','Bien Unido','Bilar','Buenavista','Calape','Candijay','Carmen',
			    			'Catigbian','Clarin','Corella','Cortes','Dagohoy','Danao','Dauis','Dimiao',
			    			'Duero','Garcia Hernandez','Getafe','Guindulman','Inabanga','Jagna','Lila',
			    			'Loay','Loboc','Loon','Mabini','Maribojoc','Panglao','Pilar',
			    			'President Carlos P. Garcia','Sagbayan','San Isidro','San Miguel',
			    			'Sevilla','Sierra Bullones','Sikatuna','Talibon','Trinidad','Tubigon',
			    			'Ubay','Valencia'),
			    	'Bukidnon' => array('Baungon','Cabanglasan','Damulog','Dangcagan','Don Carlos',
			    			'Impasug-ong','Kadingilan','Kalilangan','Kibawe','Kitaotao','Lantapan',
			    			'Libona','Malitbog','Manolo Fortich','Maramag','Pangantucan','Quezon',
			    			'San Fernando','Sumilao','Talakag'),
			    	'Bulacan' => array('Angat','Balagtas','Baliuag','Bocaue','Bulacan','Bustos',
			    			'Calumpit','Doña Remedios Trinidad','Guiguinto','Hagonoy','Marilao',
			    			'Norzagaray','Obando','Pandi','Paombong','Plaridel','Pulilan',
			    			'San Ildefonso','San Miguel','San Rafael','Santa Maria'),
			    	'Cagayan' => array('Abulug','Alcala','Allacapan','Amulung','Aparri','Baggao',
			    			'Ballesteros','Buguey','Calayan','Camalaniugan','Claveria','Enrile',
			    			'Gattaran','Gonzaga','Iguig','Lal-lo','Lasam','Pamplona','Peñablanca',
			    			'Piat','Rizal','Sanchez-Mira','Santa Ana','Santa Praxedes',
			    			'Santa Teresita','Santo Niño','Solana','Tuao'),
		    		'Camarines Norte' => array('Basud','Capalonga','Daet','Jose Panganiban','Labo',
			    			'Mercedes','Paracale','San Lorenzo Ruiz','San Vicente','Santa Elena',
			    			'Talisay','Vinzons'),
		    		'Camarines Sur' => array('Baao','Balatan','Bato','Bombon','Buhi','Bula',
			    			'Cabusao','Calabanga','Camaligan','Canaman','Caramoan','Del Gallego',
			    			'Gainza','Garchitorena','Goa','Lagonoy','Libmanan','Lupi','Magarao',
			    			'Milaor','Minalabac','Nabua','Ocampo','Pamplona','Pasacao','Pili',
			    			'Presentacion','Ragay','Sagñay','San Fernando','San Jose','Sipocot',
			    			'Siruma','Tigaon','Tinambac'),
		    		'Camiguin' => array('Catarman','Guinsiliban','Mahinog','Mambajao','Sagay'),
		    		'Capiz' => array('Cuartero','Dao','Dumalag','Dumarao','Ivisan','Jamindan',
		    				'Ma-ayon','Mambusao','Panay','Panitan','Pilar','Pontevedra',
		    				'President Roxas','Sapi-an','Sigma','Tapaz'),
		    		'Catanduanes' => array('Bagamanoc','Baras','Bato','Caramoran','Gigmoto',
		    				'Pandan','Panganiban','San Andres','San Miguel','Viga','Virac'),
		    		'Cavite' => array('Alfonso','Amadeo','Carmona','General Mariano Alvarez',
		    				'General Emilio Aguinaldo','General Trias','Indang','Kawit',
		    				'Magallanes','Maragondon','Mendez','Naic','Noveleta','Rosario',
		    				'Silang','Tanza','Ternate'),
		    		'Cebu' => array('Alcantara','Alcoy','Alegria','Aloguinsan','Argao','Asturias',
		    				'Badian','Balamban','Bantayan','Barili','Boljoon','Borbon','Carmen',
		    				'Catmon','Compostela','Consolacion','Cordoba','Daanbantayan',
		    				'Dalaguete','Dumanjug','Ginatilan','Liloan','Madridejos','Malabuyoc',
		    				'Medellin','Minglanilla','Moalboal','Oslob','Pilar','Pinamungahan',
		    				'Poro','Ronda','Samboan','San Fernando','San Francisco','San Remigio',
		    				'Santa Fe','Santander','Sibonga','Sogod','Tabogon','Tabuelan','Tuburan',
		    				'Tudela'),
		    		'Compostela Valley' => array('Compostela','Laak','Mabini','Maco','Maragusan',
		    				'Mawab','Monkayo','Montevista','Nabunturan','New Bataan','Pantukan'),
		    		'Cotabato' => array('Alamada','Aleosan','Antipas','Arakan','Banisilan','Carmen',
		    				'Kabacan','Libungan','M\'lang','Magpet','Makilala','Matalam','Midsayap',
		    				'Pigkawayan','Pikit','President Roxas','Tulunan'),
		    		'Davao del Norte' => array('Asuncion','Braulio E. Dujali','Carmen','Kapalong',
		    				'New Corella','San Isidro','Santo Tomas','Talaingod'),
		    		'Davao del Sur' => array('Bansalan','Hagonoy','Kiblawan','Magsaysay','Malalag',
		    				'Matanao','Padada','Santa Cruz','Sarangani','Sulop'),
		    		'Davao Occidental' => array('Don Marcelino','Jose Abad Santos','Malita',
		    				'Santa Maria','Sarangani'),
		    		'Davao Oriental' => array('Baganga','Banaybanay','Boston','Caraga','Cateel',
		    				'Governor Generoso','Lupon','Manay','San Isidro','Tarragona'),
		    		'Dinagat Islands' => array('Basilisa (Rizal)','Cagdianao','Dinagat',
		    				'Libjo (Albor)','Loreto','San Jose','Tubajon'),
		    		'Eastern Samar' => array('Arteche','Balangiga','Balangkayan','Can-avid',
		    				'Dolores','General MacArthur','Giporlos','Guiuan','Hernani','Jipapad',
		    				'Lawaan','Llorente','Maslog','Maydolong','Mercedes','Oras','Quinapondan',
		    				'Salcedo','San Julian','San Policarpo','Sulat','Taft'),
		    		'Guimaras' => array('Buenavista','Jordan','Nueva Valencia','San Lorenzo',
		    				'Sibunag'),
		    		'Ifugao' => array('Aguinaldo','Alfonso Lista','Asipulo','Banaue','Hingyon',
		    				'Hungduan','Kiangan','Lagawe','Lamut','Mayoyao','Tinoc'),
		    		'Ilocos Norte' => array('Adams','Bacarra','Badoc','Bangui','Banna','Burgos',
		    				'Carasi','Currimao','Dingras','Dumalneg','Marcos','Nueva Era',
		    				'Pagudpud','Paoay','Pasuquin','Piddig','Pinili','San Nicolas',
		    				'Sarrat','Solsona','Vintar'),
		    		'Ilocos Sur' => array('Alilem','Banayoyo','Bantay','Burgos','Cabugao','Caoayan',
		    				'Cervantes','Galimuyod','Gregorio Del Pilar','Lidlidda','Magsingal',
		    				'Nagbukel','Narvacan','Quirino','Salcedo','San Emilio','San Esteban',
		    				'San Ildefonso','San Juan','San Vicente','Santa','Santa Catalina',
		    				'Santa Cruz','Santa Lucia','Santa Maria','Santiago','Santo Domingo',
		    				'Sigay','Sinait','Sugpon','Suyo','Tagudin'),
		    		'Iloilo' => array('Ajuy','Alimodian','Anilao','Badiangan','Balasan','Banate',
		    				'Barotac Nuevo','Barotac Viejo','Batad','Bingawan','Cabatuan','Calinog',
		    				'Carles','Concepcion','Dingle','Dueñas','Dumangas','Estancia','Guimbal',
		    				'Igbaras','Janiuay','Lambunao','Leganes','Lemery','Leon','Maasin',
		    				'Miagao','Mina','New Lucena','Oton','Pavia','Pototan','San Dionisio',
		    				'San Enrique','San Joaquin','San Miguel','San Rafael','Santa Barbara',
		    				'Sara','Tigbauan','Tubungan','Zarraga'),
		    		'Isabela' => array('Alicia','Angadanan','Aurora','Benito Soliven','Burgos',
		    				'Cabagan','Cabatuan','Cordon','Delfin Albano','Dinapigue','Divilacan',
		    				'Echague','Gamu','Jones','Luna','Maconacon','Mallig','Naguilian',
		    				'Palanan','Quezon','Quirino','Ramon','Reina Mercedes','Roxas',
		    				'San Agustin','San Guillermo','San Isidro','San Manuel','San Mariano',
		    				'San Mateo','San Pablo','Santa Maria','Santo Tomas','Tumauini'),
		    		'Kalinga' => array('Balbalan','Lubuagan','Pasil','Pinukpuk','Rizal','Tanudan',
		    				'Tinglayan'),
		    		'La Union' => array('Agoo','Aringay','Bacnotan','Bagulin','Balaoan','Bangar',
		    				'Bauang','Burgos','Caba','Luna','Naguilian','Pugo','Rosario',
		    				'San Gabriel','San Juan','Santo Tomas','Santol','Sudipen','Tubao'),
		    		'Laguna' => array('Alaminos','Bay','Calauan','Cavinti','Famy','Kalayaan',
		    				'Liliw','Los Baños','Luisiana','Lumban','Mabitac','Magdalena','Majayjay',
		    				'Nagcarlan','Paete','Pagsanjan','Pakil','Pangil','Pila','Rizal',
		    				'Santa Cruz','Santa Maria','Siniloan','Victoria'),
		    		'Lanao del Norte' => array('Bacolod','Baloi','Baroy','Kapatagan','Kauswagan',
		    				'Kolambugan','Lala','Linamon','Magsaysay','Maigo','Matungao','Munai',
		    				'Nunungan','Pantao Ragat','Pantar','Poona Piagapo','Salvador','Sapad',
		    				'Sultan Naga Dimaporo','Tagoloan','Tangcal','Tubod'),
		    		'Lanao del Sur' => array('Bacolod-Kalawi','Balabagan','Balindong','Bayang',
		    				'Binidayan','Buadiposo-Buntong','Bubong','Bumbaran','Butig','Calanogas',
		    				'Ditsaan-Ramain','Ganassi','Kapai','Kapatagan','Lumba-Bayabao',
		    				'Lumbaca-Unayan','Lumbatan','Lumbayanague','Madalum','Madamba','Maguing',
		    				'Malabang','Marantao','Marogong','Masiu','Mulondo','Pagayawan','Piagapo',
		    				'Poona Bayabao','Pualas','Saguiaran','Sultan Dumalondong','Picong',
		    				'Tagoloan II','Tamparan','Taraka','Tubaran','Tugaya','Wao'),
		    		'Leyte' => array('Abuyog','Alangalang','Albuera','Babatngon','Barugo','Bato',
		    				'Burauen','Calubian','Capoocan','Carigara','Dagami','Dulag','Hilongos',
		    				'Hindang','Inopacan','Isabel','Jaro','Javier','Julita','Kananga',
		    				'La Paz','Leyte','MacArthur','Mahaplag','Matag-ob','Matalom','Mayorga',
		    				'Merida','Palo','Palompon','Pastrana','San Isidro','San Miguel',
		    				'Santa Fe','Tabango','Tabontabon','Tanauan','Tolosa','Tunga','Villaba'),
		    		'Maguindanao' => array('Ampatuan','Barira','Buldon','Buluan',
		    				'Datu Abdullah Sangki','Datu Anggal Midtimbang','Datu Blah T. Sinsuat',
		    				'Datu Hoffer Ampatuan','Datu Montawal','Datu Odin Sinsuat','Datu Paglas',
		    				'Datu Piang','Datu Salibo','Datu Saudi-Ampatuan','Datu Unsay',
		    				'General Salipada K. Pendatun','Guindulungan','Kabuntalan','Mamasapano',
		    				'Mangudadatu','Matanog','Northern Kabuntalan','Pagalungan','Paglat',
		    				'Pandag','Parang','Rajah Buayan','Shariff Aguak','Shariff Saydona Mustapha',
		    				'South Upi','Sultan Kudarat','Sultan Mastura','Sultan sa Barongis',
		    				'Talayan','Talitay','Upi'),
		    		'Marinduque' => array('Boac','Buenavista','Gasan','Mogpog','Santa Cruz','Torrijos'),
		    		'Masbate' => array('Aroroy','Baleno','Balud','Batuan','Cataingan','Cawayan',
		    				'Claveria','Dimasalang','Esperanza','Mandaon','Milagros','Mobo','Monreal',
		    				'Palanas','Pio V. Corpuz','Placer','San Fernando','San Jacinto',
		    				'San Pascual','Uson'),
		    		'Metro Manila' => array('Pateros'),
		    		'Misamis Occidental' => array('Aloran','Baliangao','Bonifacio','Calamba',
		    				'Clarin','Concepcion','Don Victoriano Chiongbian','Jimenez','Lopez Jaena',
		    				'Panaon','Plaridel','Sapang Dalaga','Sinacaban','Tudela'),
		    		'Misamis Oriental' => array('Alubijid','Balingasag','Balingoan','Binuangan',
		    				'Claveria','Gitagum','Initao','Jasaan','Kinoguitan','Lagonglong',
		    				'Laguindingan','Libertad','Lugait','Magsaysay','Manticao','Medina',
		    				'Naawan','Opol','Salay','Sugbongcogon','Tagoloan','Talisayan',
		    				'Villanueva'),
		    		'Mountain Province' => array('Barlig','Bauko','Besao','Bontoc','Natonin',
		    				'Paracelis','Sabangan','Sadanga','Sagada','Tadian'),
		    		'Negros Occidental' => array('Binalbagan','Calatrava','Candoni','Cauayan',
		    				'Enrique B. Magalona','Hinigaran','Hinoba-an','Ilog','Isabela',
		    				'La Castellana','Manapla','Moises Padilla','Murcia','Pontevedra',
		    				'Pulupandan','Salvador Benedicto','San Enrique','Toboso','Valladolid'),
		    		'Negros Oriental' => array('Amlan','Ayungon','Bacong','Basay','Bindoy','Dauin',
		    				'Jimalalud','La Libertad','Mabinay','Manjuyod','Pamplona','San Jose',
		    				'Santa Catalina','Siaton','Sibulan','Tayasan','Valencia','Vallehermoso',
		    				'Zamboanguita'),
		    		'Northern Samar' => array('Allen','Biri','Bobon','Capul','Catarman','Catubig',
		    				'Gamay','Laoang','Lapinig','Las Navas','Lavezares','Lope de Vega',
		    				'Mapanas','Mondragon','Palapag','Pambujan','Rosario','San Antonio',
		    				'San Isidro','San Jose','San Roque','San Vicente','Silvino Lobos',
		    				'Victoria'),
		    		'Nueva Ecija' => array('Aliaga','Bongabon','Cabiao','Carranglan','Cuyapo',
		    				'Gabaldon','General Mamerto Natividad','General Tinio','Guimba','Jaen',
		    				'Laur','Licab','Llanera','Lupao','Nampicuan','Pantabangan','Peñaranda',
		    				'Quezon','Rizal','San Antonio','San Isidro','San Leonardo','Santa Rosa',
		    				'Santo Domingo','Talavera','Talugtug','Zaragoza'),
		    		'Nueva Vizcaya' => array('Alfonso Castaneda','Ambaguio','Aritao','Bagabag',
		    				'Bambang','Bayombong','Diadi','Dupax del Norte','Dupax del Sur','Kasibu',
		    				'Kayapa','Quezon','Santa Fe','Solano','Villaverde'),
		    		'Occidental Mindoro' => array('Abra de Ilog','Calintaan','Looc','Lubang',
		    				'Magsaysay','Mamburao','Paluan','Rizal','Sablayan','San Jose',
		    				'Santa Cruz'),
		    		'Oriental Mindoro' => array('Baco','Bansud','Bongabong','Bulalacao','Gloria',
		    				'Mansalay','Naujan','Pinamalayan','Pola','Puerto Galera','Roxas',
		    				'San Teodoro','Socorro','Victoria'),
		    		'Palawan' => array('Aborlan','Agutaya','Araceli','Balabac','Bataraza',
		    				'Brooke\'s Point','Busuanga','Cagayancillo','Coron','Culion','Cuyo',
		    				'Dumaran','El Nido','Kalayaan','Linapacan','Magsaysay','Narra','Quezon',
		    				'Rizal','Roxas','San Vicente','Sofronio Española','Taytay'),
		    		'Pampanga' => array('Apalit','Arayat','Bacolor','Candaba','Floridablanca',
		    				'Guagua','Lubao','Macabebe','Magalang','Masantol','Mexico','Minalin',
		    				'Porac','San Luis','San Simon','Santa Ana','Santa Rita','Santo Tomas',
		    				'Sasmuan'),
		    		'Pangasinan' => array('Agno','Aguilar','Alcala','Anda','Asingan','Balungao',
		    				'Bani','Basista','Bautista','Bayambang','Binalonan','Binmaley','Bolinao',
		    				'Bugallon','Burgos','Calasiao','Dasol','Infanta','Labrador','Laoac',
		    				'Lingayen','Mabini','Malasiqui','Manaoag','Mangaldan','Mangatarem',
		    				'Mapandan','Natividad','Pozzorubio','Rosales','San Fabian','San Jacinto',
		    				'San Manuel','San Nicolas','San Quintin','Santa Barbara','Santa Maria',
		    				'Santo Tomas','Sison','Sual','Tayug','Umingan','Urbiztondo','Villasis'),
		    		'Quezon' => array('Agdangan','Alabat','Atimonan','Buenavista','Burdeos','Calauag',
		    				'Candelaria','Catanauan','Dolores','General Luna','General Nakar',
		    				'Guinayangan','Gumaca','Infanta','Jomalig','Lopez','Lucban','Macalelon',
		    				'Mauban','Mulanay','Padre Burgos','Pagbilao','Panukulan','Patnanungan',
		    				'Perez','Pitogo','Plaridel','Polillo','Quezon','Real','Sampaloc',
		    				'San Andres','San Antonio','San Francisco','San Narciso','Sariaya',
		    				'Tagkawayan','Tiaong','Unisan'),
		    		'Quirino' => array('Aglipay','Cabarroguis','Diffun','Maddela','Nagtipunan',
		    				'Saguday'),
		    		'Rizal' => array('Angono','Baras','Binangonan','Cainta','Cardona','Jalajala',
		    				'Morong','Pililla','Rodriguez','San Mateo','Tanay','Taytay','Teresa'),
		    		'Romblon' => array('Alcantara','Banton','Cajidiocan','Calatrava','Concepcion',
		    				'Corcuera','Ferrol','Looc','Magdiwang','Odiongan','Romblon',
		    				'San Agustin','San Andres','San Fernando','San Jose','Santa Fe',
		    				'Santa Maria'),
		    		'Samar' => array('Almagro','Basey','Calbiga','Daram','Gandara','Hinabangan',
		    				'Jiabong','Marabut','Matuguinao','Motiong','Pagsanghan','Paranas',
		    				'Pinabacdao','San Jorge','San Jose De Buan','San Sebastian',
		    				'Santa Margarita','Santa Rita','Santo Niño','Tagapul-an','Talalora',
		    				'Tarangnan','Villareal','Zumarraga'),
		    		'Sarangani' => array('Alabel','Glan','Kiamba','Maasim','Maitum','Malapatan',
		    				'Malungon'),
		    		'Siquijor' => array('Enrique Villanueva','Larena','Lazi','Maria','San Juan',
		    				'Siquijor'),
		    		'Sorsogon' => array('Barcelona','Bulan','Bulusan','Casiguran','Castilla',
		    				'Donsol','Gubat','Irosin','Juban','Magallanes','Matnog','Pilar',
		    				'Prieto Diaz','Santa Magdalena'),
		    		'South Cotabato' => array('Polomolok','Banga','Lake Sebu','Norala','Santo Niño',
		    				'Surallah','T\'boli','Tampakan','Tantangan','Tupi'),
		    		'Southern Leyte' => array('Anahawan','Bontoc','Hinunangan','Hinundayan','Libagon',
		    				'Liloan','Limasawa','Macrohon','Malitbog','Padre Burgos','Pintuyan',
		    				'Saint Bernard','San Francisco','San Juan','San Ricardo','Silago','Sogod',
		    				'Tomas Oppus'),
		    		'Sultan Kudarat' => array('Bagumbayan','Columbio','Esperanza','Isulan',
		    				'Kalamansig','Lambayong','Lebak','Lutayan','Palimbang','President Quirino',
		    				'Senator Ninoy Aquino'),
		    		'Sulu' => array('Banguingui','Hadji Panglima Tahil','Indanan','Jolo',
		    				'Kalingalan Caluang','Lugus','Luuk','Maimbung','Old Panamao','Omar',
		    				'Pandami','Panglima Estino','Pangutaran','Parang','Pata','Patikul',
		    				'Siasi','Talipao','Tapul'),
		    		'Surigao del Norte' => array('Alegria','Bacuag','Burgos','Claver','Dapa','Del Carmen',
		    				'General Luna','Gigaquit','Mainit','Malimono','Pilar','Placer','San Benito',
		    				'San Francisco','San Isidro','Santa Monica','Sison','Socorro','Tagana-an',
		    				'Tubod'),
		    		'Surigao del Sur' => array('Barobo','Bayabas','Cagwait','Cantilan','Carmen',
		    				'Carrascal','Cortes','Hinatuan','Lanuza','Lianga','Lingig','Madrid',
		    				'Marihatag','San Agustin','San Miguel','Tagbina','Tago'),
		    		'Tarlac' => array('Anao','Bamban','Camiling','Capas','Concepcion','Gerona',
		    				'La Paz','Mayantoc','Moncada','Paniqui','Pura','Ramos','San Clemente',
		    				'San Jose','San Manuel','Santa Ignacia','Victoria'),
		    		'Tawi-Tawi' => array('Bongao','Languyan','Mapun','Panglima Sugala','Sapa-Sapa',
		    				'Sibutu','Simunul','Sitangkai','South Ubian','Tandubas','Turtle Islands'),
		    		'Zambales' => array('Botolan','Cabangan','Candelaria','Castillejos','Iba',
		    				'Masinloc','Palauig','San Antonio','San Felipe','San Marcelino',
		    				'San Narciso','Santa Cruz','Subic'),
		    		'Zamboanga del Norte' => array('Bacungan','Baliguian','Godod','Gutalac',
		    				'Jose Dalman','Kalawit','Katipunan','La Libertad','Labason','Liloy',
		    				'Manukan','Mutia','Piñan','Polanco','President Manuel A. Roxas','Rizal',
		    				'Salug','Sergio Osmeña Sr.','Siayan','Sibuco','Sibutad','Sindangan',
		    				'Siocon','Sirawai','Tampilisan'),
		    		'Zamboanga del Sur' => array('Aurora','Bayog','Dimataling','Dinas','Dumalinao',
		    				'Dumingag','Guipos','Josefina','Kumalarang','Labangan','Lakewood',
		    				'Lapuyan','Mahayag','Margosatubig','Midsalip','Molave','Pitogo',
		    				'Ramon Magsaysay','San Miguel','San Pablo','Sominot','Tabina','Tambulig',
		    				'Tigbao','Tukuran','Vincenzo A. Sagun'),
		    		'Zamboanga Sibugay' => array('Alicia','Buug','Diplahan','Imelda','Ipil',
		    				'Kabasalan','Mabuhay','Malangas','Naga','Olutanga','Payao','Roseller Lim',
		    				'Siay','Talusan','Titay','Tungawan')
		    		);
	public	$component_cities = array(
					'Abra' => array(),
					'Agusan del Norte' => array('Cabadbaran City'),
					'Agusan del Sur' => array('Bayugan City'),
					'Aklan' => array(),
					'Albay' => array('Legazpi City','Ligao City','Tabaco City'),
					'Antique' => array(),
					'Apayao' => array(),
					'Aurora' => array(),
					'Basilan' => array('Isabela City','Lamitan City'),
					'Bataan' => array('Balanga City'),
					'Batanes' => array(),
					'Batangas' => array('Batangas City','Lipa City','Tanauan City'),
					'Benguet' => array(),
					'Biliran' => array(),
					'Bohol' => array('Tagbilaran City'),
					'Bukidnon' => array('Malaybalay City','Valencia City'),
					'Bulacan' => array('Malolos City','Meycauayan City','San Jose del Monte City'),
					'Cagayan' => array('Tuguegarao City'),
		    		'Camarines Norte' => array(),
		    		'Camarines Sur' => array('Iriga City'),
		    		'Camiguin' => array(),
		    		'Capiz' => array('Roxas City'),
		    		'Catanduanes' => array(),
		    		'Cavite' => array('Bacoor City','Cavite City','Dasmariñas City','Imus City',
		    				'Tagaytay City','Trece Martires City'),
		    		'Cebu' => array('Bogo City','Carcar City','Danao City','Naga City',
		    				'Talisay City','Toledo City'),
		    		'Compostela Valley' => array(),
		    		'Cotabato' => array('Kidapawan City'),
		    		'Davao del Norte' => array('Panabo City','Samal City','Tagum City'),
		    		'Davao del Sur' => array('Digos City'),
		    		'Davao Occidental' => array(),
		    		'Davao Oriental' => array('Mati City'),
		    		'Dinagat Islands' => array(),
		    		'Eastern Samar' => array('Borongan City'),
		    		'Guimaras' => array(),
		    		'Ifugao' => array(),
		    		'Ilocos Norte' => array('Batac City','Laoag City'),
		    		'Ilocos Sur' => array('Candon City','Vigan City'),
		    		'Iloilo' => array('Passi City'),
		    		'Isabela' => array('Cauayan City','Ilagan City'),
		    		'Kalinga' => array('Tabuk City'),
		    		'La Union' => array('San Fernando City'),
		    		'Laguna' => array('Biñan City','Cabuyao City','Calamba City','San Pablo City',
		    				'San Pedro City','Santa Rosa City'),
		    		'Lanao del Norte' => array(),
		    		'Lanao del Sur' => array('Marawi City'),
		    		'Leyte' => array('Baybay City'),
		    		'Maguindanao' => array(),
		    		'Marinduque' => array(),
		    		'Masbate' => array('Masbate City'),
		    		'Metro Manila' => array(),
		    		'Misamis Occidental' => array('Oroquieta City','Ozamiz City','Tangub City'),
		    		'Misamis Oriental' => array('El Salvador City','Gingoog City'),
		    		'Mountain Province' => array(),
		    		'Negros Occidental' => array('Bago City','Cadiz City','Escalante City',
		    				'Himamaylan City','Kabankalan City','La Carlota City','Sagay City',
		    				'San Carlos City','Silay City','Sipalay City','Talisay City',
		    				'Victorias City'),
		    		'Negros Oriental' => array('Bais City','Bayawan City','Canlaon City',
		    				'Guihulngan City','Dumaguete City','Tanjay City'),
		    		'Northern Samar' => array(),
		    		'Nueva Ecija' => array('Gapan City','Palayan City','San Jose City',
		    				'Science City of Muñoz'),
		    		'Nueva Vizcaya' => array(),
		    		'Occidental Mindoro' => array(),
		    		'Oriental Mindoro' => array('Calapan City'),
		    		'Palawan' => array(),
		    		'Pampanga' => array('San Fernando City','Mabalacat City'),
		    		'Pangasinan' => array('Alaminos City','San Carlos City','Urdaneta City'),
		    		'Quezon' => array('Tayabas City'),
		    		'Quirino' => array(),
		    		'Rizal' => array('Antipolo City'),
		    		'Romblon' => array(),
		    		'Samar' => array('Calbayog City','Catbalogan City'),
		    		'Sarangani' => array(),
		    		'Siquijor' => array(),
		    		'Sorsogon' => array('Sorsogon City'),
		    		'South Cotabato' => array('Koronadal City'),
		    		'Southern Leyte' => array('Maasin City'),
		    		'Sultan Kudarat' => array('Tacurong City'),
		    		'Sulu' => array(),
		    		'Surigao del Norte' => array('Surigao City'),
		    		'Surigao del Sur' => array('Bislig City','Tandag City'),
		    		'Tarlac' => array('Tarlac City'),
		    		'Tawi-Tawi' => array(),
		    		'Zambales' => array(),
		    		'Zamboanga del Norte' => array('Dapitan City','Dipolog City'),
		    		'Zamboanga del Sur' => array('Pagadian City'),
		    		'Zamboanga Sibugay' => array()
				);
	public	$independent_component_cities = array(
					'Abra' => array(),
					'Agusan del Norte' => array(),
					'Agusan del Sur' => array(),
					'Aklan' => array(),
					'Albay' => array(),
					'Antique' => array(),
					'Apayao' => array(),
					'Aurora' => array(),
					'Basilan' => array(),
					'Bataan' => array(),
					'Batanes' => array(),
					'Batangas' => array(),
					'Benguet' => array(),
					'Biliran' => array(),
					'Bohol' => array(),
					'Bukidnon' => array(),
					'Bulacan' => array(),
					'Cagayan' => array(),
		    		'Camarines Norte' => array(),
		    		'Camarines Sur' => array('Naga City'),
		    		'Camiguin' => array(),
		    		'Capiz' => array(),
		    		'Catanduanes' => array(),
		    		'Cavite' => array(),
		    		'Cebu' => array(),
		    		'Compostela Valley' => array(),
		    		'Cotabato' => array(),
		    		'Davao del Norte' => array(),
		    		'Davao del Sur' => array(),
		    		'Davao Occidental' => array(),
		    		'Davao Oriental' => array(),
		    		'Dinagat Islands' => array(),
		    		'Eastern Samar' => array(),
		    		'Guimaras' => array(),
		    		'Ifugao' => array(),
		    		'Ilocos Norte' => array(),
		    		'Ilocos Sur' => array(),
		    		'Iloilo' => array(),
		    		'Isabela' => array('Santiago City'),
		    		'Kalinga' => array(),
		    		'La Union' => array(),
		    		'Laguna' => array(),
		    		'Lanao del Norte' => array(),
		    		'Lanao del Sur' => array(),
		    		'Leyte' => array('Ormoc City'),
		    		'Maguindanao' => array('Cotabato City'),
		    		'Marinduque' => array(),
		    		'Masbate' => array(),
		    		'Metro Manila' => array(),
		    		'Misamis Occidental' => array(),
		    		'Misamis Oriental' => array(),
		    		'Mountain Province' => array(),
		    		'Negros Occidental' => array(),
		    		'Negros Oriental' => array(),
		    		'Northern Samar' => array(),
		    		'Nueva Ecija' => array(),
		    		'Nueva Vizcaya' => array(),
		    		'Occidental Mindoro' => array(),
		    		'Oriental Mindoro' => array(),
		    		'Palawan' => array(),
		    		'Pampanga' => array(),
		    		'Pangasinan' => array('Dagupan City'),
		    		'Quezon' => array(),
		    		'Quirino' => array(),
		    		'Rizal' => array(),
		    		'Romblon' => array(),
		    		'Samar' => array(),
		    		'Sarangani' => array(),
		    		'Siquijor' => array(),
		    		'Sorsogon' => array(),
		    		'South Cotabato' => array(),
		    		'Southern Leyte' => array(),
		    		'Sultan Kudarat' => array(),
		    		'Sulu' => array(),
		    		'Surigao del Norte' => array(),
		    		'Surigao del Sur' => array(),
		    		'Tarlac' => array(),
		    		'Tawi-Tawi' => array(),
		    		'Zambales' => array(),
		    		'Zamboanga del Norte' => array(),
		    		'Zamboanga del Sur' => array(),
		    		'Zamboanga Sibugay' => array()
				);
	public	$highly_urbanized_cities = array(
					'Abra' => array(),
					'Agusan del Norte' => array('Butuan City'),
					'Agusan del Sur' => array(),
					'Aklan' => array(),
					'Albay' => array(),
					'Antique' => array(),
					'Apayao' => array(),
					'Aurora' => array(),
					'Basilan' => array(),
					'Bataan' => array(),
					'Batanes' => array(),
					'Batangas' => array(),
					'Benguet' => array('Baguio City'),
					'Biliran' => array(),
					'Bohol' => array(),
					'Bukidnon' => array(),
					'Bulacan' => array(),
					'Cagayan' => array(),
		    		'Camarines Norte' => array(),
		    		'Camarines Sur' => array(),
		    		'Camiguin' => array(),
		    		'Capiz' => array(),
		    		'Catanduanes' => array(),
		    		'Cavite' => array(),
		    		'Cebu' => array('Cebu City','Lapu-Lapu City','Mandaue City'),
		    		'Compostela Valley' => array(),
		    		'Cotabato' => array(),
		    		'Davao del Norte' => array(),
		    		'Davao del Sur' => array('Davao City'),
		    		'Davao Occidental' => array(),
		    		'Davao Oriental' => array(),
		    		'Dinagat Islands' => array(),
		    		'Eastern Samar' => array(),
		    		'Guimaras' => array(),
		    		'Ifugao' => array(),
		    		'Ilocos Norte' => array(),
		    		'Ilocos Sur' => array(),
		    		'Iloilo' => array('Iloilo City'),
		    		'Isabela' => array(),
		    		'Kalinga' => array(),
		    		'La Union' => array(),
		    		'Laguna' => array(),
		    		'Lanao del Norte' => array('Iligan City'),
		    		'Lanao del Sur' => array(),
		    		'Leyte' => array('Tacloban City'),
		    		'Maguindanao' => array(),
		    		'Marinduque' => array(),
		    		'Masbate' => array(),
		    		'Metro Manila' => array('City of Manila','Caloocan','Las Piñas','Makati',
		    				'Malabon','Mandaluyong','Marikina','Muntinlupa','Navotas','Parañaque',
		    				'Pasay','Pasig','Quezon City','San Juan','Taguig','Valenzuela'),
		    		'Misamis Occidental' => array(),
		    		'Misamis Oriental' => array('Cagayan de Oro'),
		    		'Mountain Province' => array(),
		    		'Negros Occidental' => array('Bacolod City'),
		    		'Negros Oriental' => array(),
		    		'Northern Samar' => array(),
		    		'Nueva Ecija' => array('Cabanatuan City'),
		    		'Nueva Vizcaya' => array(),
		    		'Occidental Mindoro' => array(),
		    		'Oriental Mindoro' => array(),
		    		'Palawan' => array('Puerto Princesa City'),
		    		'Pampanga' => array('Angeles City'),
		    		'Pangasinan' => array(),
		    		'Quezon' => array('Lucena City'),
		    		'Quirino' => array(),
		    		'Rizal' => array(),
		    		'Romblon' => array(),
		    		'Samar' => array(),
		    		'Sarangani' => array(),
		    		'Siquijor' => array(),
		    		'Sorsogon' => array(),
		    		'South Cotabato' => array('General Santos City'),
		    		'Southern Leyte' => array(),
		    		'Sultan Kudarat' => array(),
		    		'Sulu' => array(),
		    		'Surigao del Norte' => array(),
		    		'Surigao del Sur' => array(),
		    		'Tarlac' => array(),
		    		'Tawi-Tawi' => array(),
		    		'Zambales' => array('Olongapo City'),
		    		'Zamboanga del Norte' => array(),
		    		'Zamboanga del Sur' => array('Zamboanga City'),
		    		'Zamboanga Sibugay' => array()
				);
	public function __construct()
	{
        $this->ci =& get_instance();
	}

	public function getProvinces()
	{
		$arr_provinces = $this->provinces;
		return $arr_provinces;
	}

	public function getMunicipalities($province)
	{
		$arr_municipalities = in_array($province, $this->provinces) ? $this->municipalities[$province] : array();
		return $arr_municipalities;
	}

	public function getComponentCities($province)
	{
		$arr_component_cities = in_array($province, $this->provinces) ? $this->component_cities[$province] : array();
		return $arr_component_cities;
	}

	public function getIndependentComponentCities($province)
	{
		$arr_independent_component_cities = in_array($province, $this->provinces) ? $this->independent_component_cities[$province] : array();
		return $arr_independent_component_cities;
	}

	public function getHighlyUrbanizedCities($province)
	{
		$arr_highly_urbanized_cities = in_array($province, $this->provinces) ? $this->highly_urbanized_cities[$province] : array();
		return $arr_highly_urbanized_cities;
	}	
}

/* End of file Location.php */
/* Location: ./application/libraries/Location.php */
